/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as CheckoutCanceladoRouteImport } from './routes/checkout.cancelado'

const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCanceladoRoute = CheckoutCanceladoRouteImport.update({
  id: '/cancelado',
  path: '/cancelado',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRoute
  '/checkout/cancelado': typeof CheckoutCanceladoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRoute
  '/checkout/cancelado': typeof CheckoutCanceladoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRoute
  '/checkout/cancelado': typeof CheckoutCanceladoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/checkout'
    | '/conta'
    | '/checkout/cancelado'
    | '/checkout/sucesso'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/checkout'
    | '/conta'
    | '/checkout/cancelado'
    | '/checkout/sucesso'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buscar'
    | '/checkout'
    | '/conta'
    | '/checkout/cancelado'
    | '/checkout/sucesso'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContaRoute: typeof ContaRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/cancelado': {
      id: '/checkout/cancelado'
      path: '/cancelado'
      fullPath: '/checkout/cancelado'
      preLoaderRoute: typeof CheckoutCanceladoRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutCanceladoRoute: typeof CheckoutCanceladoRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCanceladoRoute: CheckoutCanceladoRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContaRoute: ContaRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
