/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as NichoSlugRouteImport } from './routes/nicho.$slug'
import { Route as ContaPedidosRouteImport } from './routes/conta.pedidos'
import { Route as ContaDadosRouteImport } from './routes/conta.dados'
import { Route as ColecaoSlugRouteImport } from './routes/colecao.$slug'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as CheckoutCanceladoRouteImport } from './routes/checkout.cancelado'

const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NichoSlugRoute = NichoSlugRouteImport.update({
  id: '/nicho/$slug',
  path: '/nicho/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ContaRoute,
} as any)
const ContaDadosRoute = ContaDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => ContaRoute,
} as any)
const ColecaoSlugRoute = ColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCanceladoRoute = CheckoutCanceladoRouteImport.update({
  id: '/cancelado',
  path: '/cancelado',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRouteWithChildren
  '/kits': typeof KitsRoute
  '/checkout/cancelado': typeof CheckoutCanceladoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/conta/dados': typeof ContaDadosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/nicho/$slug': typeof NichoSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRouteWithChildren
  '/kits': typeof KitsRoute
  '/checkout/cancelado': typeof CheckoutCanceladoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/conta/dados': typeof ContaDadosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/nicho/$slug': typeof NichoSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRouteWithChildren
  '/kits': typeof KitsRoute
  '/checkout/cancelado': typeof CheckoutCanceladoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/conta/dados': typeof ContaDadosRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/nicho/$slug': typeof NichoSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/checkout'
    | '/conta'
    | '/kits'
    | '/checkout/cancelado'
    | '/checkout/sucesso'
    | '/colecao/$slug'
    | '/conta/dados'
    | '/conta/pedidos'
    | '/nicho/$slug'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/checkout'
    | '/conta'
    | '/kits'
    | '/checkout/cancelado'
    | '/checkout/sucesso'
    | '/colecao/$slug'
    | '/conta/dados'
    | '/conta/pedidos'
    | '/nicho/$slug'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buscar'
    | '/checkout'
    | '/conta'
    | '/kits'
    | '/checkout/cancelado'
    | '/checkout/sucesso'
    | '/colecao/$slug'
    | '/conta/dados'
    | '/conta/pedidos'
    | '/nicho/$slug'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContaRoute: typeof ContaRouteWithChildren
  KitsRoute: typeof KitsRoute
  ColecaoSlugRoute: typeof ColecaoSlugRoute
  NichoSlugRoute: typeof NichoSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nicho/$slug': {
      id: '/nicho/$slug'
      path: '/nicho/$slug'
      fullPath: '/nicho/$slug'
      preLoaderRoute: typeof NichoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/dados': {
      id: '/conta/dados'
      path: '/dados'
      fullPath: '/conta/dados'
      preLoaderRoute: typeof ContaDadosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/colecao/$slug': {
      id: '/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof ColecaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/cancelado': {
      id: '/checkout/cancelado'
      path: '/cancelado'
      fullPath: '/checkout/cancelado'
      preLoaderRoute: typeof CheckoutCanceladoRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutCanceladoRoute: typeof CheckoutCanceladoRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCanceladoRoute: CheckoutCanceladoRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ContaRouteChildren {
  ContaDadosRoute: typeof ContaDadosRoute
  ContaPedidosRoute: typeof ContaPedidosRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaDadosRoute: ContaDadosRoute,
  ContaPedidosRoute: ContaPedidosRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContaRoute: ContaRouteWithChildren,
  KitsRoute: KitsRoute,
  ColecaoSlugRoute: ColecaoSlugRoute,
  NichoSlugRoute: NichoSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
